language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 7.0
    - hhvm

branches:
  only:
    - master
